<?php
session_start();
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}
require_once '../includes/config.php';
require_once '../functions/product.php';
require_once '../functions/brand.php';
require_once '../functions/category.php';
include '../includes/header.php';
include '../includes/sidebar.php';

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['add_product'])) {
    $product_name = $_POST['product_name'];
    $brand_id = $_POST['brand_id'];
    $categories_id = $_POST['categories_id'];
    $quantity = $_POST['quantity'];
    $selling_price = $_POST['selling_price'];
    $rate = $_POST['rate'];
    $active = $_POST['active'];
    $status = $_POST['status'];

    $product_image = '';
    if (isset($_FILES['product_image']) && $_FILES['product_image']['error'] == 0) {
        $target_dir = "../assets/uploads/";
        $product_image = $target_dir . basename($_FILES['product_image']['name']);
        move_uploaded_file($_FILES['product_image']['tmp_name'], $product_image);
    }

    addProduct($pdo, $product_name, $product_image, $brand_id, $categories_id, $quantity, $selling_price, $rate, $active, $status);
    header("Location: manage_products.php");
    exit();
}

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['import_csv'])) {
    if (isset($_FILES['csv_file']) && $_FILES['csv_file']['error'] == 0) {
        importProductsFromCSV($pdo, $_FILES['csv_file']['tmp_name']);
        header("Location: manage_products.php");
        exit();
    }
}

if (isset($_GET['delete'])) {
    deleteProduct($pdo, $_GET['delete']);
    header("Location: manage_products.php");
    exit();
}

$products = getProducts($pdo);
$brands = getBrands($pdo);
$categories = getCategories($pdo);
?>
 <style>
        .search-container { margin-bottom: 20px; }
        .pagination-container { margin-top: 20px; }
        .table img { max-width: 50px; }
    </style>
<div class="flex-grow-1 p-4">
    <h2>Manage Products</h2>
    <button class="btn btn-success mb-3" data-bs-toggle="modal" data-bs-target="#addProductModal">Add Product</button>
    <button class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#importCSVModal">Import CSV</button>

    <div class="container">
        <!-- Search Bar -->
        <div class="search-container">
            <input type="text" style="width: 450px;" id="searchInput" class="form-control" placeholder="Search products by name, brand, or category...">
        </div>

        <!-- Product Table -->
        <table class="table table-bordered" id="productTable">
            <thead>
                <tr>
                    <th>Product ID</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Brand</th>
                    <th>Category</th>
                    <th>Quantity</th>
                    <th>Selling Price</th>
                    <th>Rate</th>
                    <th>Active</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="productTableBody">
                <?php foreach ($products as $product): ?>
                    <tr>
                        <td><?php echo $product['product_id']; ?></td>
                        <td><?php echo $product['product_name']; ?></td>
                        <td><?php echo $product['product_image'] ? '<img src="' . $product['product_image'] . '" width="50">' : 'No Image'; ?></td>
                        <td><?php echo $product['brand_name']; ?></td>
                        <td><?php echo $product['categories_name']; ?></td>
                        <td><?php echo $product['quantity']; ?></td>
                        <td>UGX <?php echo number_format($product['selling_price'], 2); ?></td>
                        <td>UGX <?php echo number_format($product['rate'], 2); ?></td>
                        <td><?php echo $product['active'] ? 'Yes' : 'No'; ?></td>
                        <td><?php echo $product['status'] ? 'Active' : 'Inactive'; ?></td>
                        <td>
                            <a href="?delete=<?php echo $product['product_id']; ?>" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <!-- Pagination -->
        <div class="pagination-container">
            <nav>
                <ul class="pagination" id="pagination">
                    <!-- Pagination links will be generated by JavaScript -->
                </ul>
            </nav>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        const rowsPerPage = 5;
        let currentPage = 1;
        const table = document.getElementById('productTable');
        const tbody = document.getElementById('productTableBody');
        const rows = Array.from(tbody.getElementsByTagName('tr'));
        const pagination = document.getElementById('pagination');
        const searchInput = document.getElementById('searchInput');

        function displayRows(filteredRows) {
            const totalRows = filteredRows.length;
            const totalPages = Math.ceil(totalRows / rowsPerPage);

            // Update table rows
            tbody.innerHTML = '';
            const start = (currentPage - 1) * rowsPerPage;
            const end = start + rowsPerPage;
            filteredRows.slice(start, end).forEach(row => tbody.appendChild(row));

            // Update pagination
            pagination.innerHTML = '';
            for (let i = 1; i <= totalPages; i++) {
                const li = document.createElement('li');
                li.className = `page-item ${i === currentPage ? 'active' : ''}`;
                const a = document.createElement('a');
                a.className = 'page-link';
                a.href = '#';
                a.textContent = i;
                a.addEventListener('click', (e) => {
                    e.preventDefault();
                    currentPage = i;
                    displayRows(filteredRows);
                });
                li.appendChild(a);
                pagination.appendChild(li);
            }
        }

        // Search functionality
        searchInput.addEventListener('input', () => {
            const searchTerm = searchInput.value.toLowerCase();
            const filteredRows = rows.filter(row => {
                const name = row.cells[1].textContent.toLowerCase();
                const brand = row.cells[3].textContent.toLowerCase();
                const category = row.cells[4].textContent.toLowerCase();
                return name.includes(searchTerm) || brand.includes(searchTerm) || category.includes(searchTerm);
            });
            currentPage = 1; // Reset to first page
            displayRows(filteredRows);
        });

        // Previous and Next buttons
        pagination.insertAdjacentHTML('beforeend', `
            <li class="page-item">
                <a class="page-link" href="#" id="prevPage">Previous</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#" id="nextPage">Next</a>
            </li>
        `);

        document.getElementById('prevPage').addEventListener('click', (e) => {
            e.preventDefault();
            if (currentPage > 1) {
                currentPage--;
                displayRows(rows);
            }
        });

        document.getElementById('nextPage').addEventListener('click', (e) => {
            e.preventDefault();
            const totalPages = Math.ceil(rows.length / rowsPerPage);
            if (currentPage < totalPages) {
                currentPage++;
                displayRows(rows);
            }
        });

        // Initial display
        displayRows(rows);
    </script>
    <!-- Add Product Modal -->
    <div class="modal fade" id="addProductModal" tabindex="-1" aria-labelledby="addProductModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addProductModalLabel">Add Product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label for="product_name" class="form-label">Product Name</label>
                            <input type="text" class="form-control" id="product_name" name="product_name" required>
                        </div>
                        <div class="mb-3">
                            <label for="product_image" class="form-label">Product Image</label>
                            <input type="file" class="form-control" id="product_image" name="product_image">
                        </div>
                        <div class="mb-3">
                            <label for="brand_id" class="form-label">Brand</label>
                            <select class="form-control" id="brand_id" name="brand_id" required>
                                <?php foreach ($brands as $brand): ?>
                                    <option value="<?php echo $brand['brand_id']; ?>"><?php echo $brand['brand_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="categories_id" class="form-label">Category</label>
                            <select class="form-control" id="categories_id" name="categories_id" required>
                                <?php foreach ($categories as $category): ?>
                                    <option value="<?php echo $category['categories_id']; ?>"><?php echo $category['categories_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="quantity" class="form-label">Quantity</label>
                            <input type="number" class="form-control" id="quantity" name="quantity" required>
                        </div>
                        <div class="mb-3">
                            <label for="selling_price" class="form-label">Selling Price</label>
                            <input type="number" step="0.01" class="form-control" id="selling_price" name="selling_price" required>
                        </div>
                        <div class="mb-3">
                            <label for="rate" class="form-label">Rate (Cost Price)</label>
                            <input type="number" step="0.01" class="form-control" id="rate" name="rate" required>
                        </div>
                        <div class="mb-3">
                            <label for="active" class="form-label">Active</label>
                            <select class="form-control" id="active" name="active">
                                <option value="1">Yes</option>
                                <option value="0">No</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label>
                            <select class="form-control" id="status" name="status">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                        <button type="submit" name="add_product" class="btn btn-primary">Add Product</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Import CSV Modal -->
    <div class="modal fade" id="importCSVModal" tabindex="-1" aria-labelledby="importCSVModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="importCSVModalLabel">Import Products from CSV</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label for="csv_file" class="form-label">CSV File</label>
                            <input type="file" class="form-control" id="csv_file" name="csv_file" accept=".csv" required>
                        </div>
                        <button type="submit" name="import_csv" class="btn btn-primary">Import</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>